name: My First workflow

on:
 push:

jobs:
  first_job:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout repo
       uses: actions/checkout@v4
     - name: Welcome message
       run: |
             echo "this is my first workflow"
             ls -ltrah
             cat README.md

     - name: Install Cowsay Program
       run: sudo apt-get install cowsay -y

     - name: generate ASCII Artwork
       run: cowsay -f dragon "Run for cover, I am dragon" >> dragon.txt 
     - name: Read dragon files
       run: cat dragon.txt
    