name: multi jobs workflow

on:
 push:

jobs:
  first_job:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout repo
       uses: actions/checkout@v4
     - name: install cowsay program
       run: sudo apt-get install cowsay -y

     - name: execute
       run: cowsay -f dragon "Run for cover, I am dragon" >> dragon.txt 
     - name: upload artifact 
       uses: actions/upload-artifact@v3
       with:
          name: dragon-text-file
          path: dragon.txt
  
  test_job-2:
     needs: [first_job]
     runs-on: ubuntu-latest
     steps:
     - name: Download dragon.txt
       uses: actions/download-artifact@v3
       with:
          name: dragon-text-file
     - name: test file exists
       run: grep -i "dragon" dragon.txt

  test_job-3:
     needs: [test_job-2]
     runs-on: ubuntu-latest
     steps:
       - name: Download dragon.txt
         uses: actions/download-artifact@v3
         with:
          name: dragon-text-file
       - name: read file
         run: cat dragon.txt
       - name: Deploy
         run: echo "Deploying....."