name: multi jobs workflow

on:
 push:

jobs:
  first_job:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout repo
       uses: actions/checkout@v4
     - name: install cowsay program
       run: sudo apt-get install cowsay -y

     - name: execute
       run: cowsay -f dragon "Run for cover, I am dragon" >> dragon.txt 
     - name: sleep for 30 sec
       run: sleep 30
  
  test_job-2:
  needs: [first_job]
     runs-on: ubuntu-latest
     steps:
     - name: sleep for 10 sec
       run: sleep 10
     - name: test file exists
       run: grep -i "dragon" dragon.txt

  test_job-3:
     needs: [test_job-2]
     runs-on: ubuntu-latest
     steps:
       - name: read file
         run: cat dragon.txt
       - name: Deploy
         run: echo "Deploying....."