name: workflow dispatch event

on:
  workflow_dispatch:
    

jobs:
  workflowdispatchjob:
     runs-on: ubuntu-latest
     steps:
     - name: this is scheudle job
       run: echo "this is scheudle job"